(function(){
const LS='runpilot_v15_state';
const today=()=>new Date().toISOString().slice(0,10);
const dateAdd=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const n=(v,d=0)=>{const x=Number(v);return Number.isFinite(x)?x:d};
const defaultState=()=>({version:15,profile:{sex:'male',age:27,height:165,weight:71.5,activity:1.55},settings:{theme:'light'},usmle:{dailyQTarget:40,dailyAnkiTarget:300,blocks:[]},nutritionLogs:{},run:{weekTarget:50,runsPerWeek:3,plan:[],logs:{}},updatedAt:null});
let state=load();let sb=null;let user=null;let sync='Локально';
function load(){try{return {...defaultState(),...(JSON.parse(localStorage.getItem(LS))||{})}}catch{return defaultState()}}
function saveLocal(){state.updatedAt=new Date().toISOString();localStorage.setItem(LS,JSON.stringify(state));}
function byDate(obj,d=today()){return obj&&obj[d]?obj[d]:null}
function initSupabase(){const c=window.RUNPILOT_CONFIG||{};if(!c.SUPABASE_URL||!c.SUPABASE_PUBLISHABLE_KEY||!window.supabase)return;sb=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_PUBLISHABLE_KEY);}
async function syncLoad(){if(!sb)return;const {data:{session}}=await sb.auth.getSession();user=session?.user||null;if(!user){sync='Локально';renderSync();return;}sync='Синхронизация';renderSync();const table=(window.RUNPILOT_CONFIG||{}).TABLE||'marathon_data';const {data,error}=await sb.from(table).select('data').eq('user_id',user.id).maybeSingle();if(!error&&data?.data){state={...defaultState(),...data.data};saveLocal();}sync='Синхронизировано';renderSync();}
async function persist(){saveLocal();renderSync();if(!sb||!user)return;const table=(window.RUNPILOT_CONFIG||{}).TABLE||'marathon_data';sync='Синхронизация';renderSync();const {error}=await sb.from(table).upsert({user_id:user.id,data:state,updated_at:new Date().toISOString()},{onConflict:'user_id'});sync=error?'Ошибка синхронизации':'Синхронизировано';renderSync();}
function renderSync(){document.querySelectorAll('[data-sync]').forEach(el=>el.textContent=sync)}
function getUsmleToday(){const d=today();const blocks=(state.usmle.blocks||[]).filter(b=>b.date===d);const q=blocks.reduce((s,b)=>s+n(b.questions),0);const c=blocks.reduce((s,b)=>s+n(b.correct),0);const anki=blocks.reduce((s,b)=>s+n(b.anki),0);const reviewed=blocks.reduce((s,b)=>s+n(b.reviewed),0);return{q,c,anki,reviewed,rate:q?Math.round(c/q*100):0}}
function runCaloriesForDate(d=today()){const log=state.run.logs?.[d];const kg=n(byDate(state.nutritionLogs,d)?.weight,state.profile.weight);return Math.round(n(log?.km)*kg);} // скрыто в беге, видно только в калораже
function bmr(){const p=state.profile;const kg=n(byDate(state.nutritionLogs,today())?.weight,p.weight);const base=10*kg+6.25*n(p.height,165)-5*n(p.age,27)+(p.sex==='female'?-161:5);return Math.round(base)}
function dailyBaseBurn(){return Math.round(bmr()*n(state.profile.activity,1.55))}
function calorieStats(d=today()){const log=byDate(state.nutritionLogs,d)||{};const target=n(log.target,2200);const eaten=n(log.calories,0);const base=dailyBaseBurn();const run=runCaloriesForDate(d);return{target,eaten,base,run,totalBurn:base+run,left:target-eaten+run}}
function weekKm(){const now=new Date();const day=(now.getDay()+6)%7;const mon=dateAdd(today(),-day);let sum=0;for(let i=0;i<7;i++){const d=dateAdd(mon,i);sum+=n(state.run.logs?.[d]?.km)}return Math.round(sum*10)/10}
function plannedToday(){return (state.run.plan||[]).find(p=>p.date===today())}
function bar(label,value,target){const pct=target?clamp(value/target*100,0,100):0;return `<div class="bar-row"><div class="bar-label"><span>${label}</span><b>${value} / ${target}</b></div><div class="bar"><span style="width:${pct}%"></span></div></div>`}
function renderHome(){const u=getUsmleToday();const cal=calorieStats();const wk=weekKm();set('[data-home-usmle]',`${u.q}/40 Q`);set('[data-home-calories]',`${cal.left} ккал`);set('[data-home-run]',`${wk} км/нед`)}
function set(sel,txt){document.querySelectorAll(sel).forEach(e=>e.textContent=txt)}
function renderUsmle(){const u=getUsmleToday();set('[data-usmle-today-q]',`${u.q} / ${state.usmle.dailyQTarget}`);set('[data-usmle-today-rate]',`${u.rate}%`);set('[data-usmle-today-anki]',`${u.anki} / ${state.usmle.dailyAnkiTarget}`);const bars=document.getElementById('usmle-bars');if(bars)bars.innerHTML=bar('QBank',u.q,state.usmle.dailyQTarget)+bar('Anki',u.anki,state.usmle.dailyAnkiTarget)+bar('Ошибки разобраны',u.reviewed,Math.max(1,u.q-u.c));const blocks=document.getElementById('usmle-blocks');if(blocks){const arr=[...(state.usmle.blocks||[])].slice(-8).reverse();blocks.innerHTML=arr.length?arr.map(b=>`<div class="list-item"><div><b>${b.system} · ${b.mode}</b><small>${b.date} · ${b.source} · ${b.note||''}</small></div><b>${b.questions?Math.round(b.correct/b.questions*100):0}%</b></div>`).join(''):'<div class="empty">Блоков пока нет.</div>'}renderWeak();chartUsmle('usmle-chart')}
function renderWeak(){const el=document.getElementById('weak-systems');if(!el)return;const map={};(state.usmle.blocks||[]).forEach(b=>{if(!map[b.system])map[b.system]={q:0,c:0};map[b.system].q+=n(b.questions);map[b.system].c+=n(b.correct)});const rows=Object.entries(map).filter(([k,v])=>k!=='mixed'&&v.q>0).map(([k,v])=>({k,rate:Math.round(v.c/v.q*100),q:v.q})).sort((a,b)=>a.rate-b.rate).slice(0,5);el.className='list';el.innerHTML=rows.length?rows.map(r=>`<div class="list-item"><b>${r.k}</b><span>${r.rate}% · ${r.q}Q</span></div>`).join(''):'<div class="empty">Пока мало данных.</div>'}
function renderCalories(){const c=calorieStats();set('[data-cal-left]',c.left);set('[data-cal-eaten]',c.eaten);set('[data-cal-base]',c.base);set('[data-cal-run]',c.run);set('[data-cal-total-burn]',c.totalBurn);const log=byDate(state.nutritionLogs,today())||{};const m=document.getElementById('macro-bars');if(m)m.innerHTML=bar('Белки',n(log.protein),140)+bar('Жиры',n(log.fat),60)+bar('Углеводы',n(log.carbs),250);chartWeight('weight-chart')}
function renderRun(){const p=plannedToday();const log=byDate(state.run.logs,today())||{};set('[data-run-today]',log.km?`${log.km} км факт`:p?`${p.km} км · ${p.type}`:'План не задан');set('[data-run-today-sub]',log.minutes?`${log.minutes} мин · ${log.type}`:p?'Плановая тренировка':'Создай план или запиши факт.');set('[data-run-week]',`${weekKm()} км`);set('[data-run-week-target]',`${state.run.weekTarget} км`);set('[data-run-rpe]',log.rpe||'—');const list=document.getElementById('run-plan-list');if(list){const arr=(state.run.plan||[]).filter(p=>p.date>=dateAdd(today(),-1)).slice(0,7);list.innerHTML=arr.length?arr.map(p=>`<div class="list-item"><div><b>${p.date}</b><small>${p.type}</small></div><b>${p.km} км</b></div>`).join(''):'<div class="empty">План не создан.</div>'}chartRun('run-chart')}
function renderStats(){chartUsmle('stats-usmle');chartWeight('stats-weight');chartRun('stats-run')}
function setupForms(){const uf=document.getElementById('usmle-form');if(uf)uf.onsubmit=e=>{e.preventDefault();const f=new FormData(uf);state.usmle.blocks.push({id:crypto.randomUUID(),date:today(),source:f.get('source'),mode:f.get('mode'),system:f.get('system'),questions:n(f.get('questions')),correct:n(f.get('correct')),anki:n(f.get('anki')),reviewed:n(f.get('reviewed')),note:f.get('note')||'',createdAt:new Date().toISOString()});persist().then(renderUsmle);uf.reset();};const cf=document.getElementById('calorie-form');if(cf)cf.onsubmit=e=>{e.preventDefault();const f=new FormData(cf);state.nutritionLogs[today()]={...(state.nutritionLogs[today()]||{}),calories:n(f.get('calories')),target:n(f.get('target')),weight:n(f.get('weight')),protein:n(f.get('protein')),fat:n(f.get('fat')),carbs:n(f.get('carbs')),updatedAt:new Date().toISOString()};state.profile.weight=n(f.get('weight'),state.profile.weight);persist().then(renderCalories)};const pf=document.getElementById('profile-form');if(pf)pf.onsubmit=e=>{e.preventDefault();const f=new FormData(pf);state.profile={...state.profile,sex:f.get('sex'),age:n(f.get('age')),height:n(f.get('height')),activity:n(f.get('activity'))};persist().then(renderCalories)};const rf=document.getElementById('run-log-form');if(rf){const d=rf.querySelector('[name=date]');if(d)d.value=today();rf.onsubmit=e=>{e.preventDefault();const f=new FormData(rf);const date=f.get('date')||today();state.run.logs[date]={km:n(f.get('km')),minutes:n(f.get('minutes')),rpe:n(f.get('rpe')),type:f.get('type'),updatedAt:new Date().toISOString()};persist().then(renderRun)}}const rpf=document.getElementById('run-plan-form');if(rpf)rpf.onsubmit=e=>{e.preventDefault();const f=new FormData(rpf);state.run.weekTarget=n(f.get('weekTarget'),50);state.run.runsPerWeek=n(f.get('runsPerWeek'),3);state.run.plan=makePlan(state.run.weekTarget,state.run.runsPerWeek);persist().then(renderRun)};const af=document.getElementById('auth-form');if(af)af.onsubmit=async e=>{e.preventDefault();if(!sb){alert('Supabase не настроен в config.js');return}const submit=e.submitter?.value;const f=new FormData(af);const email=f.get('email'),password=f.get('password');const res=submit==='signup'?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(res.error)alert(res.error.message);await syncLoad();renderAuth()};const lo=document.getElementById('logout');if(lo)lo.onclick=async()=>{if(sb)await sb.auth.signOut();user=null;sync='Локально';renderAuth();renderSync()}}
function makePlan(target,runs){const days=runs>=5?[1,2,4,5,6]:runs===4?[1,3,5,6]:[2,4,6];const plan=[];const base=target/(runs+1.2);for(let w=0;w<4;w++){days.slice(0,runs).forEach((day,i)=>{const mon=dateAdd(today(),w*7+day);const km=i===days.slice(0,runs).length-1?Math.round(base*1.8):Math.round(base*(i===1?1.1:.8));plan.push({date:mon,km,type:i===days.slice(0,runs).length-1?'Long':i===1?'Tempo':'Easy'})})}return plan}
function labels(days=30){return Array.from({length:days},(_,i)=>dateAdd(today(),i-days+1))}
function chart(id, cfg){const el=document.getElementById(id);if(!el||!window.Chart)return;const old=Chart.getChart(el);if(old)old.destroy();new Chart(el,cfg)}
function chartUsmle(id){const ds=labels(14);chart(id,{type:'line',data:{labels:ds.map(d=>d.slice(5)),datasets:[{label:'Correct %',data:ds.map(d=>{const arr=(state.usmle.blocks||[]).filter(b=>b.date===d);const q=arr.reduce((s,b)=>s+n(b.questions),0),c=arr.reduce((s,b)=>s+n(b.correct),0);return q?Math.round(c/q*100):null}),tension:.35}]},options:{responsive:true,scales:{y:{min:0,max:100}}}})}
function chartWeight(id){const ds=labels(30);chart(id,{type:'bar',data:{labels:ds.map(d=>d.slice(5)),datasets:[{type:'line',label:'Вес',data:ds.map(d=>byDate(state.nutritionLogs,d)?.weight||null),yAxisID:'y1',tension:.35},{type:'bar',label:'Дефицит/остаток',data:ds.map(d=>calorieStats(d).left),yAxisID:'y'}]},options:{responsive:true,scales:{y:{position:'left'},y1:{position:'right',grid:{drawOnChartArea:false}}}}})}
function chartRun(id){const ds=labels(30);chart(id,{type:'bar',data:{labels:ds.map(d=>d.slice(5)),datasets:[{label:'Км',data:ds.map(d=>n(state.run.logs?.[d]?.km))}]},options:{responsive:true}})}
function renderAuth(){const el=document.getElementById('auth-status');if(!el)return;el.innerHTML=`<div class="list-item"><b>Режим</b><span>${sync}</span></div><div class="list-item"><b>User</b><span>${user?.email||'Гость'}</span></div>`}
async function boot(){initSupabase();setupForms();await syncLoad();const page=document.body.dataset.page;renderSync();if(page==='home')renderHome();if(page==='usmle')renderUsmle();if(page==='calories')renderCalories();if(page==='run')renderRun();if(page==='stats')renderStats();if(page==='auth')renderAuth();}
boot();
})();
